spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  datasource:
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson.property-naming-strategy: SNAKE_CASE

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASS}

jwt:
  secret-key: ${JWT_SECRET}
  access.exp: ${JWT_ACCESS_EXP}
  refresh.exp: ${JWT_REFRESH_EXP}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}